# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qs_ai.contracts.workflow import workflow_pb2 as workflow__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/qsai.workflow.v1.Commands/Start',
                request_serializer=workflow__pb2.StartCommand.SerializeToString,
                response_deserializer=workflow__pb2.Receipt.FromString,
                _registered_method=True)
        self.Change = channel.unary_unary(
                '/qsai.workflow.v1.Commands/Change',
                request_serializer=workflow__pb2.ChangeCommand.SerializeToString,
                response_deserializer=workflow__pb2.Receipt.FromString,
                _registered_method=True)


class CommandsServicer:
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=workflow__pb2.StartCommand.FromString,
                    response_serializer=workflow__pb2.Receipt.SerializeToString,
            ),
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=workflow__pb2.ChangeCommand.FromString,
                    response_serializer=workflow__pb2.Receipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.Commands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.Commands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Commands:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Commands/Start',
            workflow__pb2.StartCommand.SerializeToString,
            workflow__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Commands/Change',
            workflow__pb2.ChangeCommand.SerializeToString,
            workflow__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResultsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Accept = channel.unary_unary(
                '/qsai.workflow.v1.Results/Accept',
                request_serializer=workflow__pb2.StateEvent.SerializeToString,
                response_deserializer=workflow__pb2.Acknowledgement.FromString,
                _registered_method=True)


class ResultsServicer:
    """Missing associated documentation comment in .proto file."""

    def Accept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResultsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Accept': grpc.unary_unary_rpc_method_handler(
                    servicer.Accept,
                    request_deserializer=workflow__pb2.StateEvent.FromString,
                    response_serializer=workflow__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.Results', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.Results', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Results:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Accept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Results/Accept',
            workflow__pb2.StateEvent.SerializeToString,
            workflow__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EvaluationManagementStub:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Create',
                request_serializer=workflow__pb2.EvaluationCreateCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Start',
                request_serializer=workflow__pb2.EvaluationStartCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Get',
                request_serializer=workflow__pb2.EvaluationQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ResolveUnknown = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ResolveUnknown',
                request_serializer=workflow__pb2.UnknownResolutionCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Review = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Review',
                request_serializer=workflow__pb2.EvaluationReviewCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ListCandidates = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ListCandidates',
                request_serializer=workflow__pb2.EvaluationQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationCandidateIndex.FromString,
                _registered_method=True)
        self.GetCandidate = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/GetCandidate',
                request_serializer=workflow__pb2.EvaluationCandidateQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationCandidateEvidence.FromString,
                _registered_method=True)
        self.PreviewGates = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/PreviewGates',
                request_serializer=workflow__pb2.EvaluationGateQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationGatePreview.FromString,
                _registered_method=True)
        self.Finalize = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Finalize',
                request_serializer=workflow__pb2.EvaluationFinalizeCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ReopenReview = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ReopenReview',
                request_serializer=workflow__pb2.EvaluationReopenCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)


class EvaluationManagementServicer:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    def Create(self, request, context):
        """The caller reuses scope.run_id for retries of the identical creation request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Explicitly schedules an existing frozen requested Run; does not call a model inline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveUnknown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Review(self, request, context):
        """QS authorizes the selected review role; AI records the trusted operator and server time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewGates(self, request, context):
        """Read-only complete gate preview; does not approve the Run or publish a release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Recompute gates under CAS; this records approval/rejection, never publishes a release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReopenReview(self, request, context):
        """Reopen eligible semantic-review signatures, preserving the complete previous round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluationManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=workflow__pb2.EvaluationCreateCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=workflow__pb2.EvaluationStartCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=workflow__pb2.EvaluationQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ResolveUnknown': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveUnknown,
                    request_deserializer=workflow__pb2.UnknownResolutionCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=workflow__pb2.EvaluationReviewCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ListCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidates,
                    request_deserializer=workflow__pb2.EvaluationQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationCandidateIndex.SerializeToString,
            ),
            'GetCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidate,
                    request_deserializer=workflow__pb2.EvaluationCandidateQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationCandidateEvidence.SerializeToString,
            ),
            'PreviewGates': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewGates,
                    request_deserializer=workflow__pb2.EvaluationGateQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationGatePreview.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=workflow__pb2.EvaluationFinalizeCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ReopenReview': grpc.unary_unary_rpc_method_handler(
                    servicer.ReopenReview,
                    request_deserializer=workflow__pb2.EvaluationReopenCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.EvaluationManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.EvaluationManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EvaluationManagement:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Create',
            workflow__pb2.EvaluationCreateCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Start',
            workflow__pb2.EvaluationStartCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Get',
            workflow__pb2.EvaluationQuery.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveUnknown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ResolveUnknown',
            workflow__pb2.UnknownResolutionCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Review',
            workflow__pb2.EvaluationReviewCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ListCandidates',
            workflow__pb2.EvaluationQuery.SerializeToString,
            workflow__pb2.EvaluationCandidateIndex.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/GetCandidate',
            workflow__pb2.EvaluationCandidateQuery.SerializeToString,
            workflow__pb2.EvaluationCandidateEvidence.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewGates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/PreviewGates',
            workflow__pb2.EvaluationGateQuery.SerializeToString,
            workflow__pb2.EvaluationGatePreview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Finalize',
            workflow__pb2.EvaluationFinalizeCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReopenReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ReopenReview',
            workflow__pb2.EvaluationReopenCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
