# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from qs_ai.contracts.workflow import workflow_pb2 as workflow__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in workflow_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommandsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/qsai.workflow.v1.Commands/Start',
                request_serializer=workflow__pb2.StartCommand.SerializeToString,
                response_deserializer=workflow__pb2.Receipt.FromString,
                _registered_method=True)
        self.Change = channel.unary_unary(
                '/qsai.workflow.v1.Commands/Change',
                request_serializer=workflow__pb2.ChangeCommand.SerializeToString,
                response_deserializer=workflow__pb2.Receipt.FromString,
                _registered_method=True)


class CommandsServicer:
    """Missing associated documentation comment in .proto file."""

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Change(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=workflow__pb2.StartCommand.FromString,
                    response_serializer=workflow__pb2.Receipt.SerializeToString,
            ),
            'Change': grpc.unary_unary_rpc_method_handler(
                    servicer.Change,
                    request_deserializer=workflow__pb2.ChangeCommand.FromString,
                    response_serializer=workflow__pb2.Receipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.Commands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.Commands', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Commands:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Commands/Start',
            workflow__pb2.StartCommand.SerializeToString,
            workflow__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Change(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Commands/Change',
            workflow__pb2.ChangeCommand.SerializeToString,
            workflow__pb2.Receipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ResultsStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Accept = channel.unary_unary(
                '/qsai.workflow.v1.Results/Accept',
                request_serializer=workflow__pb2.StateEvent.SerializeToString,
                response_deserializer=workflow__pb2.Acknowledgement.FromString,
                _registered_method=True)


class ResultsServicer:
    """Missing associated documentation comment in .proto file."""

    def Accept(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResultsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Accept': grpc.unary_unary_rpc_method_handler(
                    servicer.Accept,
                    request_deserializer=workflow__pb2.StateEvent.FromString,
                    response_serializer=workflow__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.Results', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.Results', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Results:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Accept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.Results/Accept',
            workflow__pb2.StateEvent.SerializeToString,
            workflow__pb2.Acknowledgement.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EvaluationManagementStub:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Prepare',
                request_serializer=workflow__pb2.EvaluationPlanQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationPlan.FromString,
                _registered_method=True)
        self.Create = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Create',
                request_serializer=workflow__pb2.EvaluationCreateCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Start',
                request_serializer=workflow__pb2.EvaluationStartCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Cancel',
                request_serializer=workflow__pb2.EvaluationCancelCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Get',
                request_serializer=workflow__pb2.EvaluationQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ListUnknownExecutions = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ListUnknownExecutions',
                request_serializer=workflow__pb2.EvaluationUnknownQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationUnknownIndex.FromString,
                _registered_method=True)
        self.ResolveUnknown = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ResolveUnknown',
                request_serializer=workflow__pb2.UnknownResolutionCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.Review = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Review',
                request_serializer=workflow__pb2.EvaluationReviewCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ListCandidates = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ListCandidates',
                request_serializer=workflow__pb2.EvaluationQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationCandidateIndex.FromString,
                _registered_method=True)
        self.GetCandidate = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/GetCandidate',
                request_serializer=workflow__pb2.EvaluationCandidateQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationCandidateEvidence.FromString,
                _registered_method=True)
        self.PreviewGates = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/PreviewGates',
                request_serializer=workflow__pb2.EvaluationGateQuery.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationGatePreview.FromString,
                _registered_method=True)
        self.Finalize = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/Finalize',
                request_serializer=workflow__pb2.EvaluationFinalizeCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)
        self.ReopenReview = channel.unary_unary(
                '/qsai.workflow.v1.EvaluationManagement/ReopenReview',
                request_serializer=workflow__pb2.EvaluationReopenCommand.SerializeToString,
                response_deserializer=workflow__pb2.EvaluationState.FromString,
                _registered_method=True)


class EvaluationManagementServicer:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    def Prepare(self, request, context):
        """Resolve all eleven immutable references and policy budgets; no creation or scheduling.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Create(self, request, context):
        """The caller reuses scope.run_id for retries of the identical creation request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """Explicitly schedules an existing frozen requested Run; does not call a model inline.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Stop future work; dispatched/unknown calls must be completed or resolved first.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListUnknownExecutions(self, request, context):
        """Read-only version-bound uncertain calls and frozen budget; never authorizes a retry.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveUnknown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Review(self, request, context):
        """QS authorizes the selected review role; AI records the trusted operator and server time.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListCandidates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCandidate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PreviewGates(self, request, context):
        """Read-only complete gate preview; does not approve the Run or publish a release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Finalize(self, request, context):
        """Recompute gates under CAS; this records approval/rejection, never publishes a release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReopenReview(self, request, context):
        """Reopen eligible semantic-review signatures, preserving the complete previous round.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EvaluationManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=workflow__pb2.EvaluationPlanQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationPlan.SerializeToString,
            ),
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=workflow__pb2.EvaluationCreateCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=workflow__pb2.EvaluationStartCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=workflow__pb2.EvaluationCancelCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=workflow__pb2.EvaluationQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ListUnknownExecutions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUnknownExecutions,
                    request_deserializer=workflow__pb2.EvaluationUnknownQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationUnknownIndex.SerializeToString,
            ),
            'ResolveUnknown': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveUnknown,
                    request_deserializer=workflow__pb2.UnknownResolutionCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'Review': grpc.unary_unary_rpc_method_handler(
                    servicer.Review,
                    request_deserializer=workflow__pb2.EvaluationReviewCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ListCandidates': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCandidates,
                    request_deserializer=workflow__pb2.EvaluationQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationCandidateIndex.SerializeToString,
            ),
            'GetCandidate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCandidate,
                    request_deserializer=workflow__pb2.EvaluationCandidateQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationCandidateEvidence.SerializeToString,
            ),
            'PreviewGates': grpc.unary_unary_rpc_method_handler(
                    servicer.PreviewGates,
                    request_deserializer=workflow__pb2.EvaluationGateQuery.FromString,
                    response_serializer=workflow__pb2.EvaluationGatePreview.SerializeToString,
            ),
            'Finalize': grpc.unary_unary_rpc_method_handler(
                    servicer.Finalize,
                    request_deserializer=workflow__pb2.EvaluationFinalizeCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
            'ReopenReview': grpc.unary_unary_rpc_method_handler(
                    servicer.ReopenReview,
                    request_deserializer=workflow__pb2.EvaluationReopenCommand.FromString,
                    response_serializer=workflow__pb2.EvaluationState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.EvaluationManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.EvaluationManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EvaluationManagement:
    """Trusted QS backend only. QS authorizes governance writes and candidate audit reads.
    """

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Prepare',
            workflow__pb2.EvaluationPlanQuery.SerializeToString,
            workflow__pb2.EvaluationPlan.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Create',
            workflow__pb2.EvaluationCreateCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Start',
            workflow__pb2.EvaluationStartCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Cancel',
            workflow__pb2.EvaluationCancelCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Get',
            workflow__pb2.EvaluationQuery.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListUnknownExecutions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ListUnknownExecutions',
            workflow__pb2.EvaluationUnknownQuery.SerializeToString,
            workflow__pb2.EvaluationUnknownIndex.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveUnknown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ResolveUnknown',
            workflow__pb2.UnknownResolutionCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Review(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Review',
            workflow__pb2.EvaluationReviewCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListCandidates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ListCandidates',
            workflow__pb2.EvaluationQuery.SerializeToString,
            workflow__pb2.EvaluationCandidateIndex.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCandidate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/GetCandidate',
            workflow__pb2.EvaluationCandidateQuery.SerializeToString,
            workflow__pb2.EvaluationCandidateEvidence.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PreviewGates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/PreviewGates',
            workflow__pb2.EvaluationGateQuery.SerializeToString,
            workflow__pb2.EvaluationGatePreview.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Finalize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/Finalize',
            workflow__pb2.EvaluationFinalizeCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReopenReview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.EvaluationManagement/ReopenReview',
            workflow__pb2.EvaluationReopenCommand.SerializeToString,
            workflow__pb2.EvaluationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PublicationManagementStub:
    """Shared configuration catalog. QS authorizes each operator before delegation.
    Server timestamps and immutable evaluation proof are never supplied by callers.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/Publish',
                request_serializer=workflow__pb2.PublicationPublishCommand.SerializeToString,
                response_deserializer=workflow__pb2.PublicationReceipt.FromString,
                _registered_method=True)
        self.Rollback = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/Rollback',
                request_serializer=workflow__pb2.PublicationRollbackCommand.SerializeToString,
                response_deserializer=workflow__pb2.PublicationReceipt.FromString,
                _registered_method=True)
        self.Disable = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/Disable',
                request_serializer=workflow__pb2.PublicationDisableCommand.SerializeToString,
                response_deserializer=workflow__pb2.PublicationReceipt.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/Get',
                request_serializer=workflow__pb2.PublicationQuery.SerializeToString,
                response_deserializer=workflow__pb2.PublicationState.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/GetReceipt',
                request_serializer=workflow__pb2.PublicationReceiptQuery.SerializeToString,
                response_deserializer=workflow__pb2.PublicationReceipt.FromString,
                _registered_method=True)
        self.ListHistory = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/ListHistory',
                request_serializer=workflow__pb2.PublicationHistoryQuery.SerializeToString,
                response_deserializer=workflow__pb2.PublicationHistoryPage.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/qsai.workflow.v1.PublicationManagement/GetHistory',
                request_serializer=workflow__pb2.PublicationHistoryVersionQuery.SerializeToString,
                response_deserializer=workflow__pb2.PublicationReceipt.FromString,
                _registered_method=True)


class PublicationManagementServicer:
    """Shared configuration catalog. QS authorizes each operator before delegation.
    Server timestamps and immutable evaluation proof are never supplied by callers.
    """

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Rollback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Same authorized organization/operator that submitted the command; read-only.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListHistory(self, request, context):
        """QS audit-authorized global configuration history; preserves original actors.
        These reads never replay commands or select an active publication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PublicationManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=workflow__pb2.PublicationPublishCommand.FromString,
                    response_serializer=workflow__pb2.PublicationReceipt.SerializeToString,
            ),
            'Rollback': grpc.unary_unary_rpc_method_handler(
                    servicer.Rollback,
                    request_deserializer=workflow__pb2.PublicationRollbackCommand.FromString,
                    response_serializer=workflow__pb2.PublicationReceipt.SerializeToString,
            ),
            'Disable': grpc.unary_unary_rpc_method_handler(
                    servicer.Disable,
                    request_deserializer=workflow__pb2.PublicationDisableCommand.FromString,
                    response_serializer=workflow__pb2.PublicationReceipt.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=workflow__pb2.PublicationQuery.FromString,
                    response_serializer=workflow__pb2.PublicationState.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=workflow__pb2.PublicationReceiptQuery.FromString,
                    response_serializer=workflow__pb2.PublicationReceipt.SerializeToString,
            ),
            'ListHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.ListHistory,
                    request_deserializer=workflow__pb2.PublicationHistoryQuery.FromString,
                    response_serializer=workflow__pb2.PublicationHistoryPage.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=workflow__pb2.PublicationHistoryVersionQuery.FromString,
                    response_serializer=workflow__pb2.PublicationReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.PublicationManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.PublicationManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PublicationManagement:
    """Shared configuration catalog. QS authorizes each operator before delegation.
    Server timestamps and immutable evaluation proof are never supplied by callers.
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/Publish',
            workflow__pb2.PublicationPublishCommand.SerializeToString,
            workflow__pb2.PublicationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Rollback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/Rollback',
            workflow__pb2.PublicationRollbackCommand.SerializeToString,
            workflow__pb2.PublicationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/Disable',
            workflow__pb2.PublicationDisableCommand.SerializeToString,
            workflow__pb2.PublicationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/Get',
            workflow__pb2.PublicationQuery.SerializeToString,
            workflow__pb2.PublicationState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/GetReceipt',
            workflow__pb2.PublicationReceiptQuery.SerializeToString,
            workflow__pb2.PublicationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/ListHistory',
            workflow__pb2.PublicationHistoryQuery.SerializeToString,
            workflow__pb2.PublicationHistoryPage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PublicationManagement/GetHistory',
            workflow__pb2.PublicationHistoryVersionQuery.SerializeToString,
            workflow__pb2.PublicationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class PromptDraftManagementStub:
    """Draft revisions are editable governance records, never published Prompt assets.
    QS authorizes each operation. Receipt lookup is restricted to the original actor.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Create = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/Create',
                request_serializer=workflow__pb2.PromptDraftCreateCommand.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftState.FromString,
                _registered_method=True)
        self.Revise = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/Revise',
                request_serializer=workflow__pb2.PromptDraftReviseCommand.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftState.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/Get',
                request_serializer=workflow__pb2.PromptDraftQuery.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftState.FromString,
                _registered_method=True)
        self.GetLifecycle = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/GetLifecycle',
                request_serializer=workflow__pb2.PromptDraftQuery.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftLifecycle.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/GetReceipt',
                request_serializer=workflow__pb2.PromptDraftReceiptQuery.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftState.FromString,
                _registered_method=True)
        self.Freeze = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/Freeze',
                request_serializer=workflow__pb2.PromptDraftFreezeCommand.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftFreezeReceipt.FromString,
                _registered_method=True)
        self.GetFreezeReceipt = channel.unary_unary(
                '/qsai.workflow.v1.PromptDraftManagement/GetFreezeReceipt',
                request_serializer=workflow__pb2.PromptDraftReceiptQuery.SerializeToString,
                response_deserializer=workflow__pb2.PromptDraftFreezeReceipt.FromString,
                _registered_method=True)


class PromptDraftManagementServicer:
    """Draft revisions are editable governance records, never published Prompt assets.
    QS authorizes each operation. Receipt lookup is restricted to the original actor.
    """

    def Create(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Revise(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLifecycle(self, request, context):
        """Latest head and freeze state from one snapshot. Revision selectors are rejected.
        Read-only status does not grant a lease or authorize a later modification.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Freeze(self, request, context):
        """Freeze validated template syntax into a native immutable asset, not a release.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFreezeReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PromptDraftManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Create': grpc.unary_unary_rpc_method_handler(
                    servicer.Create,
                    request_deserializer=workflow__pb2.PromptDraftCreateCommand.FromString,
                    response_serializer=workflow__pb2.PromptDraftState.SerializeToString,
            ),
            'Revise': grpc.unary_unary_rpc_method_handler(
                    servicer.Revise,
                    request_deserializer=workflow__pb2.PromptDraftReviseCommand.FromString,
                    response_serializer=workflow__pb2.PromptDraftState.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=workflow__pb2.PromptDraftQuery.FromString,
                    response_serializer=workflow__pb2.PromptDraftState.SerializeToString,
            ),
            'GetLifecycle': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLifecycle,
                    request_deserializer=workflow__pb2.PromptDraftQuery.FromString,
                    response_serializer=workflow__pb2.PromptDraftLifecycle.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=workflow__pb2.PromptDraftReceiptQuery.FromString,
                    response_serializer=workflow__pb2.PromptDraftState.SerializeToString,
            ),
            'Freeze': grpc.unary_unary_rpc_method_handler(
                    servicer.Freeze,
                    request_deserializer=workflow__pb2.PromptDraftFreezeCommand.FromString,
                    response_serializer=workflow__pb2.PromptDraftFreezeReceipt.SerializeToString,
            ),
            'GetFreezeReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFreezeReceipt,
                    request_deserializer=workflow__pb2.PromptDraftReceiptQuery.FromString,
                    response_serializer=workflow__pb2.PromptDraftFreezeReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.PromptDraftManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.PromptDraftManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PromptDraftManagement:
    """Draft revisions are editable governance records, never published Prompt assets.
    QS authorizes each operation. Receipt lookup is restricted to the original actor.
    """

    @staticmethod
    def Create(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/Create',
            workflow__pb2.PromptDraftCreateCommand.SerializeToString,
            workflow__pb2.PromptDraftState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Revise(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/Revise',
            workflow__pb2.PromptDraftReviseCommand.SerializeToString,
            workflow__pb2.PromptDraftState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/Get',
            workflow__pb2.PromptDraftQuery.SerializeToString,
            workflow__pb2.PromptDraftState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLifecycle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/GetLifecycle',
            workflow__pb2.PromptDraftQuery.SerializeToString,
            workflow__pb2.PromptDraftLifecycle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/GetReceipt',
            workflow__pb2.PromptDraftReceiptQuery.SerializeToString,
            workflow__pb2.PromptDraftState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Freeze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/Freeze',
            workflow__pb2.PromptDraftFreezeCommand.SerializeToString,
            workflow__pb2.PromptDraftFreezeReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFreezeReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.PromptDraftManagement/GetFreezeReceipt',
            workflow__pb2.PromptDraftReceiptQuery.SerializeToString,
            workflow__pb2.PromptDraftFreezeReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ProfileManagementStub:
    """Register a validated immutable Profile; this does not approve or publish it.
    QS authorizes writes and reads; original command receipts retain actor scope.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/qsai.workflow.v1.ProfileManagement/Register',
                request_serializer=workflow__pb2.ProfileRegisterCommand.SerializeToString,
                response_deserializer=workflow__pb2.ProfileRegistrationReceipt.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/qsai.workflow.v1.ProfileManagement/GetReceipt',
                request_serializer=workflow__pb2.ProfileRegistrationQuery.SerializeToString,
                response_deserializer=workflow__pb2.ProfileRegistrationReceipt.FromString,
                _registered_method=True)


class ProfileManagementServicer:
    """Register a validated immutable Profile; this does not approve or publish it.
    QS authorizes writes and reads; original command receipts retain actor scope.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProfileManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=workflow__pb2.ProfileRegisterCommand.FromString,
                    response_serializer=workflow__pb2.ProfileRegistrationReceipt.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=workflow__pb2.ProfileRegistrationQuery.FromString,
                    response_serializer=workflow__pb2.ProfileRegistrationReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.ProfileManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.ProfileManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProfileManagement:
    """Register a validated immutable Profile; this does not approve or publish it.
    QS authorizes writes and reads; original command receipts retain actor scope.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.ProfileManagement/Register',
            workflow__pb2.ProfileRegisterCommand.SerializeToString,
            workflow__pb2.ProfileRegistrationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.ProfileManagement/GetReceipt',
            workflow__pb2.ProfileRegistrationQuery.SerializeToString,
            workflow__pb2.ProfileRegistrationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SuiteManagementStub:
    """Rebind retained evaluation cases to immutable assets. A new Run and approval
    are required; registration never copies a previous Run's evidence or verdict.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/qsai.workflow.v1.SuiteManagement/Register',
                request_serializer=workflow__pb2.SuiteRegisterCommand.SerializeToString,
                response_deserializer=workflow__pb2.SuiteRegistrationReceipt.FromString,
                _registered_method=True)
        self.GetReceipt = channel.unary_unary(
                '/qsai.workflow.v1.SuiteManagement/GetReceipt',
                request_serializer=workflow__pb2.SuiteRegistrationQuery.SerializeToString,
                response_deserializer=workflow__pb2.SuiteRegistrationReceipt.FromString,
                _registered_method=True)


class SuiteManagementServicer:
    """Rebind retained evaluation cases to immutable assets. A new Run and approval
    are required; registration never copies a previous Run's evidence or verdict.
    """

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReceipt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SuiteManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=workflow__pb2.SuiteRegisterCommand.FromString,
                    response_serializer=workflow__pb2.SuiteRegistrationReceipt.SerializeToString,
            ),
            'GetReceipt': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceipt,
                    request_deserializer=workflow__pb2.SuiteRegistrationQuery.FromString,
                    response_serializer=workflow__pb2.SuiteRegistrationReceipt.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.SuiteManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.SuiteManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SuiteManagement:
    """Rebind retained evaluation cases to immutable assets. A new Run and approval
    are required; registration never copies a previous Run's evidence or verdict.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.SuiteManagement/Register',
            workflow__pb2.SuiteRegisterCommand.SerializeToString,
            workflow__pb2.SuiteRegistrationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReceipt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.SuiteManagement/GetReceipt',
            workflow__pb2.SuiteRegistrationQuery.SerializeToString,
            workflow__pb2.SuiteRegistrationReceipt.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AssetCatalogStub:
    """Immutable shared definitions only; QS authorizes readers. No audit receipts or activation state.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.List = channel.unary_unary(
                '/qsai.workflow.v1.AssetCatalog/List',
                request_serializer=workflow__pb2.AssetCatalogQuery.SerializeToString,
                response_deserializer=workflow__pb2.AssetCatalogResponse.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/qsai.workflow.v1.AssetCatalog/Get',
                request_serializer=workflow__pb2.AssetCatalogGetQuery.SerializeToString,
                response_deserializer=workflow__pb2.AssetCatalogResponse.FromString,
                _registered_method=True)


class AssetCatalogServicer:
    """Immutable shared definitions only; QS authorizes readers. No audit receipts or activation state.
    """

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AssetCatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=workflow__pb2.AssetCatalogQuery.FromString,
                    response_serializer=workflow__pb2.AssetCatalogResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=workflow__pb2.AssetCatalogGetQuery.FromString,
                    response_serializer=workflow__pb2.AssetCatalogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'qsai.workflow.v1.AssetCatalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('qsai.workflow.v1.AssetCatalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AssetCatalog:
    """Immutable shared definitions only; QS authorizes readers. No audit receipts or activation state.
    """

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.AssetCatalog/List',
            workflow__pb2.AssetCatalogQuery.SerializeToString,
            workflow__pb2.AssetCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/qsai.workflow.v1.AssetCatalog/Get',
            workflow__pb2.AssetCatalogGetQuery.SerializeToString,
            workflow__pb2.AssetCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
